### ISSUE TITLE
Unable to switch Icon and show icon

### ISSUE THREAD

**Issue by Vincent0009** [kejadlen/pirate-weather.alfredworkflow#2]
I follow the description. At the Environment Variables, I set the light_icons to both true and false, also tried both export and dont export. The icon won't show up. By the way, this workflow is great! Thank you guys!

**Comment by kejadlen** [comment]
Can you see if [v5.0.0](https://github.com/kejadlen/pirate-weather.alfredworkflow/releases/tag/v5.0.0) works for you?

**Comment by Vincent0009** [comment]
Sill not showing... Tried both enabled light icons and not enabled.

**Comment by kejadlen** [comment]
Ah, okay, I think I found the problem, try [5.0.1](https://github.com/kejadlen/pirate-weather.alfredworkflow/releases/tag/v5.0.1) please!

**Comment by Vincent0009** [comment]
Yes! It works!! It looks so good now!
Just one small thing. Im not sure if it is intentional. When i pick Light theme, the icon is in black color. When i pick Dark theme, the icon is in white color.
Thank you so much! Such a great workflow!

**Comment by kejadlen** [comment]
Oh, that's a good point - I was thinking the OS/Alfred theme rather than the workflow theme. I might adjust it in a later release, we'll see.
